services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      PORT: 3001

      DATABASE_HOST: drizatx-martinez-mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: driza_martinez
      DATABASE_PASSWORD: DrizaMartinez_2025
      DATABASE_NAME: drizatx_martinez

      FRONTEND_URLS: >-
        https://martinez.app.drizatx.com,http://localhost:3000,http://localhost:3010,http://77.42.23.51:3010

      JWT_SECRET: driza-super-secret-2025
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: "http://backend:3001"
        NEXT_PUBLIC_API_MODE: "true"
        NEXT_PUBLIC_API_URL: "https://martinez.api.drizatx.com"
        NEXT_PUBLIC_BASE_URL: "https://martinez.app.drizatx.com"
        NEXT_PUBLIC_SMS_ENABLED: "false"
        NEXT_PUBLIC_PUSH_ENABLED: "false"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      BACKEND_URL: "http://backend:3001"
      NEXT_PUBLIC_API_MODE: "true"
      NEXT_PUBLIC_API_URL: "https://martinez.api.drizatx.com"
      NEXT_PUBLIC_BASE_URL: "https://martinez.app.drizatx.com"
      NEXT_PUBLIC_SMS_ENABLED: "false"
      NEXT_PUBLIC_PUSH_ENABLED: "false"
    ports:
      - "3010:3000"

networks:
  default:
    name: drizatx-martinez-net
