services:
  drizatx-dev-frontend:
    image: drizatx_stack-frontend
    container_name: drizatx-dev-frontend
    environment:
      NEXT_PUBLIC_PUSH_ENABLED: "false"
      NEXT_PUBLIC_API_MODE: "true"
      NEXT_PUBLIC_SMS_ENABLED: "false"

      # Clave: apunta al backend dev por red docker
      BACKEND_URL: "http://drizatx-dev-backend:3001"

      # Por ahora por IP/puerto (luego lo pasamos a subdominio con Nginx)
      NEXT_PUBLIC_API_URL: "http://77.42.23.51:3111"
      NEXT_PUBLIC_BASE_URL: "http://77.42.23.51:3120"
    ports:
      - "3120:3000"
    networks:
      - drizatx_dev_net
    restart: unless-stopped

networks:
  drizatx_dev_net:
    external: true
